### ISSUE TITLE
Recover and extend testsuite to work with specs-v1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/testsuite-extended#26]
# Overview

After we've started the spec-v1 library update process we've broke our `testsuite` for extended FD implementations including storage support, `tabulator`, `goodtables` etc.

# Tasks

- [x] recover `testsuite`
- [x] add tests for pandas integration
- [x] expand amount of test use cases
- [x] test data package with remote schema
- [x] increase field types coverage
- [x] add diff checks for data import/export
