### ISSUE TITLE
Implement triggers

### ISSUE THREAD

**Issue by roll** [frictionlessdata/testsuite-extended#3]
# Overview

We have https://github.com/frictionlessdata/testsuite-py repository to run integration tests. We need automatically run this tests after any change in any master branch of underlying libraries.
# Analysis

The pilot was successfully implemented for `tabulator-py` - https://github.com/frictionlessdata/tabulator-py (see `.travis.yml` and `scripts`).
# Tasks
-  [ ] tabulator-py
- [ ] jsontableschema-py
- [ ] jsontableschema-bigquery-py
- [ ] jsontableschema-pandas-py
- [ ] jsontableschema-sql-py
- [ ] datapackage-py

**Comment by roll** [comment]
Should be easy using official API - https://docs.travis-ci.com/user/triggering-builds

**Comment by roll** [comment]
https://github.com/frictionlessdata/project/issues/263

**Comment by roll** [comment]
NOT ACTUAL
We use cron builds on Travis - enough for now
